[package]
name = "ykcapi"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.97"
ykllvmwrap = { path = "../ykllvmwrap" }
ykrt = { path = "../ykrt" }
yktrace = { path = "../yktrace" }
yksmp = { path = "../yksmp" }
ykutil = { path = "../ykutil" }
llvm-sys = "130"

[features]
c_testing = []
