[package]
name = "yktrace"
version = "0.1.0"
authors = ["Edd Barrett <vext01@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
elf = "0.0"
fallible-iterator = "0.2"
ykpack = { path = "../ykpack" }
lazy_static = "1.3"
